[package]
name = "v6502"
version = "0.1.0"
authors = ["Andrew Young <andrewy@indeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
